### ISSUE TITLE
Trying to add image url uploaded by form. Not displaying

### ISSUE THREAD

**Issue by venturaEffect** [DataVizForAll/leaflet-maps-with-google-sheets#107]
Hi!

I'm trying to store images through a google form uploading file.

Stored on shareable folder on drive. 
The url get saved on spreadsheet cell automatically when submit form (on same google sheet than all the leaflet options). Map works fine.
The problem is that it doesn't display the image on the bindPopup.
Changed on map.js this line of code:

`(point['Image'] ? ('<img src="' + point['Image'] + '"></img><br>') : '') +`

into (line 178):

 `(point['Image'] ? ('<iframe src="' + point['Image'] + '"></iframe><br>') : '') +`      

saving commit but when loading again map nothing happens. In inspection still holds the img tag not the iframe. Refreshed, open as private. But still not working...

Any suggestion?   

Thank you        

[https://venturaeffect.github.io/radon222-map/](url)

**Comment by ilyankou** [comment]
Hey there:

I am not sure why your `script.js` has two `mapPoints` functions defined (also the entire file is supposed to be ~1000 lines of code, yours is double that). I recommend you reset `script.js` to the original and try again.

Alternatively try to change `<img>` to `<iframe>` here:
https://github.com/venturaEffect/radon222-map/blob/master/scripts/map.js#L1153

Let me know if that helps!

**Comment by venturaEffect** [comment]
Oops
