### ISSUE TITLE
Links on info window displays as subdomain with github url 

### ISSUE THREAD

**Issue by venturaEffect** [DataVizForAll/leaflet-maps-with-google-sheets#108]
Hi!

I've a map created with google sheets and everything works fine. The only problem that I'm encountering is that on the info window of the map points the links if I click on them they send me a relative URL of the map domain.

Example:

I have www.google.com link on info window. When I press it it sends me to :

https://venturaeffect.github.io/project/www.google.com

How can I do that it sends me to www.google.com?

Thank you!

**Comment by ilyankou** [comment]
Try changing it to https://www.google.com

**Comment by ilyankou** [comment]
@venturaEffect let me know if it helped so I can close the issue.

**Comment by venturaEffect** [comment]
Yes!

Sorry. It was right!
